services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:root@db:5432/blogapp
      - SECRET_KEY=aVeryLongAndRandomStringAtLeast32CharactersLongOrMoreIsBetter
      - EMAIL_SENDER=super.avel-2014@yandex.ru
      - EMAIL_PASSWORD=tjvewrgsehvgdsqj
    command: ["sh", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"]

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=blogapp
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "15672:15672"
      - "5672:5672"

  celeryworker:
    build: .
    command: celery -A tasks.tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - DATABASE_URL=postgresql+asyncpg://postgres:root@db:5432/blogapp
      - SECRET_KEY=aVeryLongAndRandomStringAtLeast32CharactersLongOrMoreIsBetter
      - EMAIL_SENDER=super.avel-2014@yandex.ru
      - EMAIL_PASSWORD=tjvewrgsehvgdsqj

volumes:
  db_data: